name: Refresh

on:
  workflow_dispatch:
  schedule:
    # This job runs at 19:00 UTC every Saturday
    - cron: '0 19 * * 6'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run main
        run: npm run start
        env:
          DATA: ${{ secrets.DATA }}
